основные изменения в ДЗ 16
Val2003/java-shareit pull request #10
Opened 2023-11-06 15:46 UTC by Val2003

2023-11-06 19:08 UTC, andrew-larkin requested changes
Привет! 2 из 3-х контейнеров запускаются корректно, service падает из-за ошибки при подключении к БД - там скорее всего из-за неодинакового названия параметра, я в комментах к коду указал. и по коду также местами небольшие правки требуется выполнить. Это сделать и приложение будет полностью готово.

2023-11-06 19:08 UTC, andrew-larkin commented on docker-compose.yml
> +      - POSTGRES_DB=shareit
название параметра не повторяется у сервиса

2023-11-06 19:08 UTC, andrew-larkin commented on docker-compose.yml
> +  server:
сюда еще хорошо будет добавить настройку restart on failure

2023-11-06 19:08 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
@Repository

2023-11-06 19:08 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Booking findFirstByItem_IdAndItem_Owner_IdAndStartIsBefore(
optional - оборачиваем в него, если объект ожидается в единственном экземпляре. так нужно сделать во всех репозиториях

2023-11-06 19:08 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserService userService;
опять userService появился

2023-11-06 19:08 UTC, andrew-larkin commented on server/src/main/resources/application.properties
> +#spring.datasource.password=password
закомментированный код удаляем везде

2023-11-06 19:08 UTC, andrew-larkin commented on server/Dockerfile
> +#RUN ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime
тут тоже закомментированную строку удаляем

2023-11-07 10:31 UTC, Val2003 commented on docker-compose.yml
> +  server:
добавил

2023-11-07 10:31 UTC, Val2003 commented on docker-compose.yml
> +      - POSTGRES_DB=shareit
а там эта переменная не используется

2023-11-07 11:31 UTC, Val2003 commented on server/src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
Поправил

2023-11-07 11:31 UTC, Val2003 commented on server/src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Booking findFirstByItem_IdAndItem_Owner_IdAndStartIsBefore(
Поправил

2023-11-07 11:31 UTC, Val2003 commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserService userService;
Да, поправил

2023-11-07 11:31 UTC, Val2003 commented on server/src/main/resources/application.properties
> +#spring.datasource.password=password
удалил

2023-11-07 11:34 UTC, Val2003 commented on server/Dockerfile
> +#RUN ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime
удалил

2023-11-16 05:38 UTC, merged