Add controllers
Val2003/java-shareit pull request #2
Opened 2023-07-23 18:18 UTC by Val2003

2023-07-24 15:54 UTC, andrew-larkin requested changes
Привет! Очень хороший старт. Немного усовершествуем приложение с помощью mapStruct и ResponseEntity для его приближения к реальным проектам. Плюс это облегчит дальнейшую разработку на следующие 3 спринта.

2023-07-24 15:54 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@Data
@Data не стоит использовать в моделях - она может некорректно рассчитывать хэш. Лучше заменить ее на несколько аннотаций по типу @Getter, @Setter и т.п.

2023-07-24 15:54 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemController(ItemService itemService) {
чтобы в контроллерах не создавать конструкторы, мы можем поставить над классом @RequiredArgsConstructor и тогда все переменные, помеченные как final, будут автоматом добавляться в неявный конструктор - таким образом будет обеспечено внедрение зависимости

2023-07-24 15:54 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto getItemById(@PathVariable("id") long id) {
Давай для этого приложения добавим новый класс-обертку для методов контроллера ResponseEntity - он возвращает не только json, но и http-статус, что довольно удобно. Будет выглядеть как-то так:
return ResponseEntity.ok().body(itemService.getItemById(id));
Для всех методов во всех контроллерах стоит его добавить

2023-10-24 06:27 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
Добавил

2023-10-24 06:28 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@Data
Поменял

2023-10-24 06:28 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto getItemById(@PathVariable("id") long id) {
Добавил ResponseEntity

2023-10-24 08:08 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/mapper/ItemMapper.java
> +public interface ItemMapper {
отлично! мапперы можно размещать в те же папки что и dto, то есть, не создавать отдельную папку с мапперами, а просто приложить маппер в папку в каждому сервису

2023-10-24 08:55 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                .body(itemService.createItem(userService.getUser(userId), itemDto));
Поясни пожалуйста, что зничит поглубже

2023-10-24 08:56 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +@Data
completed

2023-10-24 08:56 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/mapper/ItemMapper.java
> +public interface ItemMapper {
completed

2023-10-24 08:56 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +//@RestController
completed

2023-10-24 08:57 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private final LocalDateTime start;
completed

2023-10-24 08:57 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
completed

2023-10-24 20:47 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                .body(itemService.createItem(userService.getUser(userId), itemDto));
Убрал получение user

2023-10-27 21:15 UTC, merged