добавление основных изменений 14 ДЗ
Val2003/java-shareit pull request #8
Opened 2023-10-28 06:51 UTC by Val2003

2023-10-28 18:28 UTC, andrew-larkin requested changes
Привет! Очень хорошо, остается небольшие правки местами вставить и работа будет принята.

2023-10-28 18:28 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +
@Repository над всеми репозиториями

2023-10-28 18:28 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Booking findFirstByItem_IdAndItem_Owner_IdAndStartIsBefore(
голый объект лучше не возвращать из репозитория, т.к. мы можем нарваться на NPE. Решение - оборачивать ответ в Optional - надо во всех случаях это поправить

2023-10-28 18:28 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotBlank(message = "Item's name missing")
в строке 30 нужно возвращать dto, не объект модели

2023-10-28 18:28 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserService userService;
внедрять один сервис в другой - не лучшая идея, т.к. можно поломать транзакционность. если требуется получить user, то лучше воспользоваться userRepository

2023-10-28 18:28 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @Column(name = "creation_date")
кстати есть аннотация  @CreationTimestamp, она при создании объекта автоматом запишет дату и время. если захочешь, можно попробовать

2023-10-28 18:28 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity createUser(@RequestBody @Valid UserDto userDto) {
не, зря удалил тип, надо его оставить

2023-10-28 18:28 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity updateUser(@PathVariable("id") Long id,
и тут тоже

2023-10-29 05:56 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity createUser(@RequestBody @Valid UserDto userDto) {
completed

2023-10-29 05:57 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @Column(name = "creation_date")
Спасибо учту!

2023-10-29 05:57 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +
Completed

2023-10-29 05:58 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity updateUser(@PathVariable("id") Long id,
Completed

2023-10-29 06:26 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserService userService;
Оставил репозиторий только, через него сделал

2023-10-29 06:26 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotBlank(message = "Item's name missing")
Поменял на UserDto

2023-10-29 18:39 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Booking findFirstByItem_IdAndItem_Owner_IdAndStartIsBefore(
Поправил, добавил Optional

2023-11-02 14:57 UTC, merged