Add item requests
Val2003/java-shareit pull request #9
Opened 2023-11-04 05:10 UTC by Val2003

2023-11-04 20:21 UTC, andrew-larkin requested changes
Привет! Очень хорошо,  и функционал реализован качественно, и тесты хорошо написаны - уже ощущается опыт) правки небольшие, их внести и будем готовы к финальному этапу.

2023-11-04 20:21 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
@Repository

2023-11-04 20:21 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserService userService;
один сервис в другой не стоит внедрять - могут возникнуть проблемы с транзакционностью. если нужно достать юзера, то лучше внедрить репозиторий

2023-11-04 20:21 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +
@Repository

2023-11-04 20:21 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
@Repository

2023-11-04 20:21 UTC, andrew-larkin commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    User user;
в тестах модификаторы доступа стоит поставить ко всем переменным

2023-11-04 20:21 UTC, andrew-larkin commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplIntegrationTest.java
> +@Transactional
эту аннотацию не стоит использовать с тестами, попробуй обойтись без нее

2023-11-05 07:41 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
Поправил

2023-11-05 07:42 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserService userService;
Сделал связь через репозиторий

2023-11-05 07:42 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +
добавил

2023-11-05 07:42 UTC, Val2003 commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
добавил

2023-11-05 07:43 UTC, Val2003 commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +    User user;
добавил модификаторы всем полям в тестовых классах

2023-11-05 09:24 UTC, Val2003 commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplIntegrationTest.java
> +@Transactional
Постарался убрать

2023-11-06 12:46 UTC, merged